version: "3.8"

services:
  belito-backend:
    build:
      context: .  # Usa la raíz del proyecto correctamente
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # ✅ Ahora la raíz del proyecto se monta en /app
    env_file:
      - .env  # Carga el archivo .env correctamente
    environment:
      - ENV=production
    restart: always
